### ISSUE TITLE
Error when update to v2.0.0

### ISSUE THREAD

**Issue by magicstone1412** [pinheadmz/palmreader#14]
I got the below errors when updating from v1.0.0 to v2.0.0. Please help me

```
Error: Migrate flag 2 does not match last ID: 1
    at WalletMigrator.migrate (/root/palmreader/node_modules/hsd/lib/migrations/migrator.js:171:13)
    at async WalletDB.open (/root/palmreader/node_modules/hsd/lib/wallet/walletdb.js:192:29)
    at async Plugin.open (/root/palmreader/node_modules/hsd/lib/wallet/plugin.js:86:5)
    at async SPVNode.openPlugins (/root/palmreader/node_modules/hsd/lib/node/node.js:475:9)
    at async SPVNode.open (/root/palmreader/node_modules/hsd/lib/node/spvnode.js:181:5)
    at async start (/root/palmreader/bin/palmreader:106:3)
```

**Comment by magicstone1412** [comment]
I ran ```npm i --prod```. It looks okay now.
