### ISSUE TITLE
Errors and idea after trying

### ISSUE THREAD

**Issue by magicstone1412** [pinheadmz/palmreader#3]
First of all, thank you for making the life more easier. I have an idea to use it as a key of a multisign wallet. After the installation, I ran the following command:

```
./hsd --network main --spv --http-host 0.0.0.0 --api-key=api  --plugins=palmreader
```

Turn it off and run it again, I found that: (the error disappear when I restart machine)

1st,

```
Error: Database is closed.
    at DB.iterator (/root/hsd/node_modules/bdb/lib/db.js:339:13)
    at DB.values (/root/hsd/node_modules/bdb/lib/db.js:497:23)
    at WalletDB.getWallets (/root/hsd/lib/wallet/walletdb.js:1590:20)
    at App.loadWallet (/root/hsd/node_modules/palmreader/plugin.js:245:33)
    at Timeout._onTimeout (/root/hsd/node_modules/palmreader/plugin.js:179:22)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

2nd,
 - Can not copy the information in the windows

3rd,
 - Passphrase for creating wallet should be 2 for confirmation

4th,
 - Dropdown menu if possible

**Comment by pinheadmz** [comment]
1) not sure about this, maybe it needs an extra try/catch in case there is an error while quitting

2) i havent written the docs yet but copying text requires prior installation of `xsel`, `xclip` or `pbcopy` I will eventually be adding a button to export data as a file for users where clipboard is not an option. you can, of course, also turn off mouse reporting in your terminal and simply select text and copy.

3) fixed in 452a168caabdb0104f312abde7ddaeb2d9db68ce

4) i dont think blessed has a drop down menu component -- where would you like to see that used?

**Comment by magicstone1412** [comment]
I was playing with Palm Reader today with the latest version. It's great! As for the dropdown menu I'm not sure if it can be done with the terminal but I think it would be easy and friendly for the guys who was using File commander/Midnight Commander/Total commander. Anyway, thank you so much.

![2022-10-02 19_24_21-Window](https://user-images.githubusercontent.com/9553811/193455300-5e6ac211-e765-4374-b9c0-b25d4a0c1820.png)
