### ISSUE TITLE
Installation error on an arm64 board

### ISSUE THREAD

**Issue by magicstone1412** [pinheadmz/palmreader#8]
With the previous version, I installed it and it worked. However, it's not as perfect as I reported in the issue #3  

With Nodes v14.20.1, Palm Reader v0.1.1 runs well on Ubuntu 20. So I tried to install Palm Reader v0.1.1 with Nodejs v14.20.1 on an orange pi board using [Armbian](https://www.armbian.com/) (Debian based). Note that I also tried with newer Nodejs versions (v16 and v18) but had no success.

The installation failed with the command `npm install -g hsd palmreader`. Hence, I tried to install locally using git. There is no more error message during the installation but when I ran it the following error appeared. Please check and help me. Thanks.

```
palmreader@orangepioneplus:~$ hsd --plugins palmreader
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'palmreader'
Require stack:
- /home/palmreader/hsd/bin/node
- /home/palmreader/hsd/bin/hsd
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at FullNode.loadPlugins (/home/palmreader/hsd/lib/node/node.js:461:18)
    at FullNode.init (/home/palmreader/hsd/lib/node/fullnode.js:277:10)
    at new FullNode (/home/palmreader/hsd/lib/node/fullnode.js:189:10)
    at Object.<anonymous> (/home/palmreader/hsd/bin/node:25:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/palmreader/hsd/bin/node', '/home/palmreader/hsd/bin/hsd' ]
}
```

**Comment by pinheadmz** [comment]
Yeah global node modules may require additional setup on your system, and I think node community is trying to deprecate it anyway. You can try this:

1. git clone palmreader
2. cd palmreader
3. npm i
4. ./bin/palmreader

**Comment by magicstone1412** [comment]
It works like a charm. How can I run it with hsd --spv mode in this case? Thank you.

**Comment by pinheadmz** [comment]
spv isn't supported in that configuration yet. Have you tried reading the link from here?

https://github.com/pinheadmz/palmreader#install-globally-using-npm

**Comment by magicstone1412** [comment]
Yes I did. But installing by that method will not be successful.

And I found that my board supports Ledger as well by using command `sudo chmod 666 /dev/hidraw4` in [this link.](https://github.com/LedgerHQ/ledger-live-desktop/issues/2873)

**Comment by magicstone1412** [comment]
I scrolled my middle mouse and got the error below

```
$ ~/palmreader/bin/palmreader
TypeError: done is not a function
    at Textbox.Textarea._listener (/home/pi/palmreader/node_modules/blessed/lib/widgets/textarea.js:231:5)
    at Textbox._listener (/home/pi/palmreader/node_modules/blessed/lib/widgets/textbox.js:43:15)
    at Textbox.EventEmitter._emit (/home/pi/palmreader/node_modules/blessed/lib/events.js:98:20)
    at Textbox.EventEmitter.emit (/home/pi/palmreader/node_modules/blessed/lib/events.js:117:12)
    at Form.<anonymous> (/home/pi/palmreader/node_modules/blessed/lib/widgets/form.js:43:14)
    at Form.EventEmitter._emit (/home/pi/palmreader/node_modules/blessed/lib/events.js:94:20)
    at Textbox.EventEmitter.emit (/home/pi/palmreader/node_modules/blessed/lib/events.js:131:12)
    at Program.<anonymous> (/home/pi/palmreader/node_modules/blessed/lib/widgets/screen.js:602:15)
    at Program.emit (events.js:400:28)
    at /home/pi/palmreader/node_modules/blessed/lib/program.js:410:15
```

**Comment by pinheadmz** [comment]
Thanks, this is likely an issue with Blessed, which is a bit buggy in a few places. I have a few things I want to polish there before palmreader would ever be ready for most users
